apiVersion: v1
kind: Pod
spec:
  containers:
    - name: python3
      image: python:3.8.5
      command: 
      - cat
      tty: true
    - name: ubuntu
      image: ubuntu:20.04
      command: 
      - cat
      tty: true
